"""add_recovery_mode_to_users

Revision ID: 21a970c52546
Revises: 'f4a5b6c7d8e9'
Create Date: 2026-09-09 08:38:05.053977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a970c52546'
down_revision: Union[str, None] = 'f4a5b6c7d8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovery_mode_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('recovery_token_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('recovery_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_token_expires_at')
    op.drop_column('users', 'recovery_token_hash')
    op.drop_column('users', 'recovery_mode_enabled')
    # ### end Alembic commands ###
