"""Add inventory batches and update product and sale item models

Revision ID: 8b0cdb9050e1
Revises: '003_add_discount_to_sale_items'
Create Date: 2026-08-06 03:20:24.777311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0cdb9050e1'
down_revision: Union[str, None] = '003_add_discount_to_sale_items'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_batches',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('remaining_quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
    sa.CheckConstraint('quantity > 0', name='chk_batch_quantity_positive'),
    sa.CheckConstraint('remaining_quantity >= 0', name='chk_batch_rem_quantity_non_negative'),
    sa.CheckConstraint('unit_cost >= 0', name='chk_batch_unit_cost_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batch_product_date', 'inventory_batches', ['product_id', 'purchase_date'], unique=False)
    op.create_index(op.f('ix_inventory_batches_product_id'), 'inventory_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_purchase_date'), 'inventory_batches', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_inventory_batches_purchase_id'), 'inventory_batches', ['purchase_id'], unique=False)
    op.alter_column('products', 'purchase_price', new_column_name='opening_stock_unit_cost')
    op.add_column('sale_items', sa.Column('cogs', sa.Float(), server_default='0.0', nullable=False))
    # Note: removing server_default after column addition
    op.alter_column('sale_items', 'cogs', server_default=None)

    import uuid
    from datetime import datetime, timezone

    bind = op.get_bind()
    products = bind.execute(sa.text("SELECT id, opening_stock, opening_stock_unit_cost FROM products WHERE opening_stock > 0"))
    batches_to_insert = []
    now = datetime.now(timezone.utc)
    for row in products:
        batch_id = str(uuid.uuid4())
        batches_to_insert.append({
            'id': batch_id,
            'product_id': row[0],
            'quantity': row[1],
            'remaining_quantity': row[1],
            'unit_cost': row[2],
            'purchase_date': now,
            'created_at': now,
            'updated_at': now,
            'is_deleted': False
        })
        
    if batches_to_insert:
        op.bulk_insert(
            sa.table(
                'inventory_batches',
                sa.column('id', sa.String),
                sa.column('product_id', sa.String),
                sa.column('quantity', sa.Float),
                sa.column('remaining_quantity', sa.Float),
                sa.column('unit_cost', sa.Float),
                sa.column('purchase_date', sa.DateTime(timezone=True)),
                sa.column('created_at', sa.DateTime(timezone=True)),
                sa.column('updated_at', sa.DateTime(timezone=True)),
                sa.column('is_deleted', sa.Boolean),
            ),
            batches_to_insert
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'cogs')
    op.alter_column('products', 'opening_stock_unit_cost', new_column_name='purchase_price')
    op.drop_index(op.f('ix_inventory_batches_purchase_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_purchase_date'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_product_id'), table_name='inventory_batches')
    op.drop_index('idx_batch_product_date', table_name='inventory_batches')
    op.drop_table('inventory_batches')
    # ### end Alembic commands ###
