"""add_profile_logo_url_to_users

Revision ID: 9979569087e0
Revises: 'a36ad6c8e658'
Create Date: 2026-09-06 08:31:05.873424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9979569087e0'
down_revision: Union[str, None] = 'a36ad6c8e658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_logo_url')
    # ### end Alembic commands ###
