"""add_product_type_and_farm_transactions

Revision ID: a36ad6c8e658
Revises: 'a45d5e7001b9'
Create Date: 2026-08-25 07:18:10.504114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36ad6c8e658'
down_revision: Union[str, None] = 'a45d5e7001b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_transactions',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('tray_count', sa.Float(), nullable=True),
    sa.Column('units_per_tray', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_transactions_product_id'), 'farm_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_farm_transactions_transaction_date'), 'farm_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_farm_transactions_transaction_type'), 'farm_transactions', ['transaction_type'], unique=False)
    op.add_column('products', sa.Column('product_type', sa.String(length=20), server_default='NORMAL', nullable=False))
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_column('products', 'product_type')
    op.drop_index(op.f('ix_farm_transactions_transaction_type'), table_name='farm_transactions')
    op.drop_index(op.f('ix_farm_transactions_transaction_date'), table_name='farm_transactions')
    op.drop_index(op.f('ix_farm_transactions_product_id'), table_name='farm_transactions')
    op.drop_table('farm_transactions')
    # ### end Alembic commands ###
