"""Add advance_balance to Customer

Revision ID: a45d5e7001b9
Revises: '23a5def7de08'
Create Date: 2026-08-23 03:47:20.420119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45d5e7001b9'
down_revision: Union[str, None] = '23a5def7de08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('advance_balance', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'advance_balance')
    # ### end Alembic commands ###
